groups:
  - name: whoknows_alerts
    rules:

      # Go app container not running
      - alert: AppContainerDown
        expr: absent(container_start_time_seconds{name=~".*app.*"}) or count(container_start_time_seconds{name=~".*app.*"}) == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "WhoKnows app container is not running"
          description: "The app container has not been seen for more than 1 minute."
