services:
  app:
    image: ghcr.io/ascdevops/asc_whoknows:latest
    env_file:
      - .env
    volumes:
      - sqlite-data:/app/data
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

volumes:
  sqlite-data:
