name: Bug Report
description: Report a bug
title: "[BUG]: "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Description here
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What should happen?
      placeholder: Explain what should happen, add pictures if needed.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: What actually happens?
      placeholder: Explain what happens, add pictures if needed.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Localhost
        - VM
        - Production
    validations:
      required: true
